default: &default
  access_key_id: AKIAJD5HN5A4SMTPR53A
  secret_access_key: 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

development:
  <<: *default
  bucket: spree-essentials-20110413

test:
  <<: *default
  bucket: spree-essentials-test-q230459qw09utaosdig

production:
  <<: *default
  bucket: spree-essentials-20110413
