default: &default
  bucket: spree_essentials-q230459qw09utaosdig
  access_key_id: AKIAJD5HN5A4SMTPR53A
  secret_access_key: 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


development:
  <<: *default

test:
  <<: *default
  bucket: spree_essentials_test-q230459qw09utaosdig

production:
  <<: *default
