default: &default
  access_key_id: AKIAJD5HN5A4SMTPR53A
  secret_access_key: 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

development:
  <<: *default
  bucket: spree_essentials_dev_201104008

test:
  <<: *default
  bucket: spree_essentials_test-q230459qw09utaosdig

production:
  <<: *default
  bucket: spree_essentials_201104008
